<a href="https://colab.research.google.com/github/alibouch/TensorFlow_FSA_21-22/blob/main/Introduction_sol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atelier 1: Introduction à TensorFlow



##1.   TensorFlow 1.x




*   **Construction du graphe :**





In [ ]:
%tensorflow_version 1.x
import tensorflow as tf
print("la version selectionnée est :",tf.__name__,tf.__version__)
a = tf.constant(2) 
b = tf.constant(3) 
c = a + b 
print(c)

TensorFlow 1.x selected.
la version selectionnée est : tensorflow 1.15.2
Tensor("add:0", shape=(), dtype=int32)


*   **Evaluation en utilisant une session :**

In [ ]:
with tf.Session() as sess: 
  print(sess.run(c))

5


##2.   TensorFlow 2.x

*   **Redémarrez l'envirennement d'exécution (Ctrl+M) puis exécutez le code suivant :**








In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print("la version selectionnée est :",tf.__name__,tf.__version__)
a = tf.constant(2) 
b = tf.constant(3) 
c = a + b 
print(c)

la version selectionnée est : tensorflow 2.6.0
tf.Tensor(5, shape=(), dtype=int32)


*   **Tenseur multidimensionnels**

In [ ]:
T = tf.ones(shape = [4, 2, 3], dtype = tf.float32)
print('T=', T)
print("Type des éléments :", T.dtype)
print("Nombre de dimensions : ", T.ndim)

T= tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(4, 2, 3), dtype=float32)
Type des éléments : <dtype: 'float32'>
Nombre de dimensions :  3


*   **Rang d'un tenseur**

In [ ]:
tensor_1 = tf.constant("Agadir", tf.string)
tensor_2 = tf.constant(33, tf.float64)
tensor_3 = tf.constant([1,2,3])
print("tensor_1 est un Tenseur de rang : {}".format(tf.rank(tensor_1)))
print("tensor_2 est un Tenseur de rang : ",tf.rank(tensor_2).numpy())
print("tensor_3 est un Tenseur de rang : ",tf.rank(tensor_3).numpy())
tensor_3.shape

tensor_1 est un Tenseur de rang : 0
tensor_2 est un Tenseur de rang :  0
tensor_3 est un Tenseur de rang :  1


TensorShape([3])

*   **Forme (Shape) d'un tenseur**

In [ ]:
tensor_4 = tf.constant([[10, 11, 12], [21, 22, 23]])
print("tensor_4 est un Tenseur de forme : {}".format(tensor_4.shape))
print("La taille du deuxième axe est :", tensor_4.shape[1])
print("La taille du premier axe est :", tensor_4.shape[-1])

tensor_4 est un Tenseur de forme : (2, 3)
La taille du deuxième axe est : 3
La taille du premier axe est : 3


*   **Changer la forme d'un tenseur**

In [ ]:
tensor1 = tf.constant([[[1., 2., 3.],[4. ,5., 6.]]])  # tenseur de forme [1,2,3] 
tensor2 = tf.reshape(tensor1, [2,3,1])  # tenseur de forme [2,3,1] obtenu en changeant le forme de tensor1
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 force le tenseur à calculer la dimension à cet emplacement  

print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 2. 3.]
  [4. 5. 6.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [2.]
  [3.]]

 [[4.]
  [5.]
  [6.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


*   **Opérations sur les tenseurs**

In [ ]:
x = tf.constant([[1, 2],[3, 4]])
y = tf.constant([[5, 6],[7, 8]])

# Addition de deux tenseurs
print(tf.add(x, y), "\n")

# Multiplication de deux tenseurs
print(tf.matmul(x, y), "\n")
egaux = (x == y) #  égalité élément par élément
print(egaux)
y_pow_2=tf.square(y) # carré du tenseur y
print(y_pow_2)  

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)
tf.Tensor(
[[25 36]
 [49 64]], shape=(2, 2), dtype=int32)


*   **Découper un tenseur**

In [ ]:
x =[[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]]
T1 = tf.Variable(x, dtype=tf.int32) 

deux = T1[0,1]  # Deuxième élément de la première ligne
print(deux) 

ligne3 = T1[2]  # La troisième ligne
print(ligne3)

colonne2 = T1[:, 1]  # La deuxième colonne
print(colonne2)

ligne_1_ligne_3 = T1[1::2]  # La deuxième ligne et la quatrième ligne
print(ligne_1_ligne_3)

colonne2_ligne3_ligne4 = T1[0:2, 1] # deuxième colonne, première et deuxième ligne
print(colonne2_ligne3_ligne4)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor([ 2  5  8 11], shape=(4,), dtype=int32)
tf.Tensor(
[[ 4  5  6]
 [10 11 12]], shape=(2, 3), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)
